work_space: /afs/cern.ch/work/e/ebhal/SVJ_Condor
lhe_file_path: /afs/cern.ch/work/e/ebhal/public/SVJ_t_splitLHE
n_events: 2000
n_jobs: 50
year: 2016
alpha_d: high
process_type: "t-channel"
m_med: 2000
m_d: 10
n_f: 2
r_inv: 0.5

model_name: SVJ_t_2016_mPhi-2000_mDQ-10_rinv-0p5_aD-high
total_events: 100000
x_sec_mg: 0.1587
